### ISSUE TITLE
Missing release file for elementary OS Juno

### ISSUE THREAD

**Issue by moonmehta** [mank319/elementaryPlus#465]
The PPA doesn't have a release file for elementary OS Juno, currently in Beta-1.

**Comment by ghost** [comment]
Is there a way to install it from the source code without installing from a ppa?
When I run it from the folder get this error:

`rootsandcculture@rootsandcculture-VirtualBox:~/Downloads/elementaryPlus-master$ bash install.sh 
Traceback (most recent call last):
  File "./scripts/elementaryplus-installer.py", line 24, in <module>
    from gi.repository import Gtk, Gdk, Gio, Notify
ImportError: No module named gi.repository
`

**Comment by isneezy** [comment]
I got this when tried install from source in Juno.

`bash install.sh 
./scripts/elementaryplus-installer.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, Gio, Notify
Traceback (most recent call last):
  File "./scripts/elementaryplus-installer.py", line 24, in <module>
    from gi.repository import Gtk, Gdk, Gio, Notify
ImportError: cannot import name Notify`

Any help would be appreciated, I loved this while i was at Loki but what now???

**UPDATE:**
I've managed to install it by just coping the `path_to_this_repo/elementaryPlus` folder to `~/.icons` and activated it with the help of [elementary tweeks](https://github.com/elementary-tweaks/elementary-tweaks).  
With this setup there is no way to use the elementaryPlus configuration panel, but since Ayatana indicator are gone in juno there is no need for that.  
But any way it would be great to have the ppa working fore easy updates
